name: 'secsignal'
version: '1.0.0'
config-version: 2

profile: 'secsignal'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  secsignal:
    staging:
      +schema: STAGING
      +materialized: view
    intermediate:
      +schema: INTERMEDIATE
      +materialized: table
    marts:
      +schema: MARTS
      +materialized: table
