-- =============================================================================
-- SecSignal: Database, Schemas, Warehouse, and Roles Setup
-- Run as SYSADMIN / ACCOUNTADMIN
-- =============================================================================

-- ---------- Database ----------
CREATE DATABASE IF NOT EXISTS SECSIGNAL
    COMMENT = 'SEC EDGAR financial intelligence — agentic RAG system';

-- ---------- Schemas ----------
CREATE SCHEMA IF NOT EXISTS SECSIGNAL.RAW
    COMMENT = 'Raw ingested data from EDGAR and GCS';

CREATE SCHEMA IF NOT EXISTS SECSIGNAL.STAGING
    COMMENT = 'Cleaned and normalized staging models (dbt)';

CREATE SCHEMA IF NOT EXISTS SECSIGNAL.INTERMEDIATE
    COMMENT = 'Intermediate transforms — parsed sections, chart extracts';

CREATE SCHEMA IF NOT EXISTS SECSIGNAL.MARTS
    COMMENT = 'Business-ready fact and dimension tables';

CREATE SCHEMA IF NOT EXISTS SECSIGNAL.EVALUATION
    COMMENT = 'RAG evaluation metrics and test results';

CREATE SCHEMA IF NOT EXISTS SECSIGNAL.MONITORING
    COMMENT = 'Pipeline health, freshness checks, observability';

-- ---------- Warehouse ----------
CREATE WAREHOUSE IF NOT EXISTS SECSIGNAL_WH
    WITH
        WAREHOUSE_SIZE = 'XSMALL'
        AUTO_SUSPEND = 60
        AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE
        COMMENT = 'Primary compute for SecSignal workloads';

-- Dedicated warehouse for Cortex AI operations (embedding, parsing)
CREATE WAREHOUSE IF NOT EXISTS SECSIGNAL_CORTEX_WH
    WITH
        WAREHOUSE_SIZE = 'SMALL'
        AUTO_SUSPEND = 60
        AUTO_RESUME = TRUE
        INITIALLY_SUSPENDED = TRUE
        COMMENT = 'Cortex AI workloads — AI_PARSE_DOCUMENT, AI_EMBED, AI_EXTRACT';

-- ---------- Roles ----------
USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS SECSIGNAL_ADMIN
    COMMENT = 'Full access to SecSignal database';

CREATE ROLE IF NOT EXISTS SECSIGNAL_WRITER
    COMMENT = 'Read-write access to RAW and STAGING schemas';

CREATE ROLE IF NOT EXISTS SECSIGNAL_READER
    COMMENT = 'Read-only access to MARTS schema';

-- Role hierarchy
GRANT ROLE SECSIGNAL_READER TO ROLE SECSIGNAL_WRITER;
GRANT ROLE SECSIGNAL_WRITER TO ROLE SECSIGNAL_ADMIN;
GRANT ROLE SECSIGNAL_ADMIN TO ROLE SYSADMIN;

-- ---------- Grants: SECSIGNAL_ADMIN ----------
USE ROLE SYSADMIN;

GRANT USAGE ON DATABASE SECSIGNAL TO ROLE SECSIGNAL_ADMIN;
GRANT ALL PRIVILEGES ON ALL SCHEMAS IN DATABASE SECSIGNAL TO ROLE SECSIGNAL_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE SCHEMAS IN DATABASE SECSIGNAL TO ROLE SECSIGNAL_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE SECSIGNAL TO ROLE SECSIGNAL_ADMIN;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE SECSIGNAL TO ROLE SECSIGNAL_ADMIN;
GRANT USAGE ON WAREHOUSE SECSIGNAL_WH TO ROLE SECSIGNAL_ADMIN;
GRANT USAGE ON WAREHOUSE SECSIGNAL_CORTEX_WH TO ROLE SECSIGNAL_ADMIN;

-- ---------- Grants: SECSIGNAL_WRITER ----------
GRANT USAGE ON DATABASE SECSIGNAL TO ROLE SECSIGNAL_WRITER;
GRANT USAGE ON SCHEMA SECSIGNAL.RAW TO ROLE SECSIGNAL_WRITER;
GRANT USAGE ON SCHEMA SECSIGNAL.STAGING TO ROLE SECSIGNAL_WRITER;
GRANT USAGE ON SCHEMA SECSIGNAL.INTERMEDIATE TO ROLE SECSIGNAL_WRITER;
GRANT CREATE TABLE ON SCHEMA SECSIGNAL.RAW TO ROLE SECSIGNAL_WRITER;
GRANT CREATE TABLE ON SCHEMA SECSIGNAL.STAGING TO ROLE SECSIGNAL_WRITER;
GRANT CREATE TABLE ON SCHEMA SECSIGNAL.INTERMEDIATE TO ROLE SECSIGNAL_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SECSIGNAL.RAW TO ROLE SECSIGNAL_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SECSIGNAL.RAW TO ROLE SECSIGNAL_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA SECSIGNAL.STAGING TO ROLE SECSIGNAL_WRITER;
GRANT SELECT, INSERT, UPDATE, DELETE ON FUTURE TABLES IN SCHEMA SECSIGNAL.STAGING TO ROLE SECSIGNAL_WRITER;
GRANT USAGE ON WAREHOUSE SECSIGNAL_WH TO ROLE SECSIGNAL_WRITER;

-- ---------- Grants: SECSIGNAL_READER ----------
GRANT USAGE ON DATABASE SECSIGNAL TO ROLE SECSIGNAL_READER;
GRANT USAGE ON SCHEMA SECSIGNAL.MARTS TO ROLE SECSIGNAL_READER;
GRANT SELECT ON ALL TABLES IN SCHEMA SECSIGNAL.MARTS TO ROLE SECSIGNAL_READER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA SECSIGNAL.MARTS TO ROLE SECSIGNAL_READER;
GRANT USAGE ON WAREHOUSE SECSIGNAL_WH TO ROLE SECSIGNAL_READER;
